### ISSUE TITLE
no neighbors

### ISSUE THREAD

**Issue by swelbo** [EvolBioInf/neighbors#2]
Hello! 

Thank you for this invaluable tool. It has proven to be exceptionally beneficial for our work!

However, we've encountered an issue with a couple of NCBI Taxonomy IDs (1309, 1310) for which we're not getting any associated neighbors. We're curious as to why this might be the case. Is there a method to broaden the search parameters to encompass a wider range of taxa?

Hope you can help 

tom

**Comment by haubold** [comment]
Thank you for pointing out this problem. The taxa you mention, 1309 and 1310, actually do return neighbors, but among these neighbors is a lone hyphen masquerading as a genome accession. This hyphen wrecks the subsequent download of genomes with `datasets`. The updated version of `neighbors` doesn't print hyphens in list mode (`-l`) any more. Thanks again for bringing this rather subtle bug to my attention, and I hope the fix helps you with your data analysis.

**Comment by swelbo** [comment]
Great thank you! That works perfectly. 

Updated: v2.0-4-g40e7ef6 > v2.0-16-ga89c0e7
